In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
sn.set()
from sklearn.linear_model import LinearRegression

from scipy import stats

In [5]:
data = pd.read_csv('/kaggle/input/heart-disease-prediction-using-logistic-regression/framingham.csv')
data.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [6]:
data.describe()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
count,4238.000000,4238.000000,4133.000000,4238.000000,4209.000000,4185.000000,4238.000000,4238.000000,4238.000000,4188.000000,4238.000000,4238.000000,4219.000000,4237.000000,3850.000000,4238.000000
mean,0.429212,49.584946,1.978950,0.494101,9.003089,0.029630,0.005899,0.310524,0.025720,236.721585,132.352407,82.893464,25.802008,75.878924,81.966753,0.151958
std,0.495022,8.572160,1.019791,0.500024,11.920094,0.169584,0.076587,0.462763,0.158316,44.590334,22.038097,11.910850,4.080111,12.026596,23.959998,0.359023
min,0.000000,32.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,83.500000,48.000000,15.540000,44.000000,40.000000,0.000000
25%,0.000000,42.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,206.000000,117.000000,75.000000,23.070000,68.000000,71.000000,0.000000
50%,0.000000,49.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,234.000000,128.000000,82.000000,25.400000,75.000000,78.000000,0.000000
75%,1.000000,56.000000,3.000000,1.000000,20.000000,0.000000,0.000000,1.000000,0.000000,263.000000,144.000000,89.875000,28.040000,83.000000,87.000000,0.000000
max,1.000000,70.000000,4.000000,1.000000,70.000000,1.000000,1.000000,1.000000,1.000000,696.000000,295.000000,142.500000,56.800000,143.000000,394.000000,1.000000

In [8]:
data.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [21]:
inputs = data[['age','male']]
target = data['currentSmoker']

In [22]:
x= sm.add_constant(inputs)
reg_log = sm.Logit(target,inputs)
res_log = reg_log.fit()

Optimization terminated successfully.
         Current function value: 0.666462
         Iterations 4

In [23]:
res_log.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:          currentSmoker   No. Observations:                 4238
Model:                          Logit   Df Residuals:                     4236
Method:                           MLE   Df Model:                            1
Date:                Mon, 10 Jul 2023   Pseudo R-squ.:                 0.03840
Time:                        22:17:09   Log-Likelihood:                -2824.5
converged:                       True   LL-Null:                       -2937.3
Covariance Type:            nonrobust   LLR p-value:                 5.441e-51
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
age           -0.0096      0.001    -11.671      0.000      -0.011      -0.008
male           0.9128      0.063     14.500      0.000       0.789       1.036
==============================================================================
"""

In [24]:
np.exp(0.9128)

## 0 is female which is the odd log here... or the # given here for ceoff of male
### this menas gender 0 has 2 times p of being a smoker..males

2.491288384118299

In [25]:
np.set_printoptions(formatter={'float': lambda x :"{0:0.2f}".format(x)})
res_log.predict()
## Below are Ps of being a smoker

array([0.63, 0.39, 0.61, ..., 0.39, 0.40, 0.38])

In [26]:
###compared to actual data
np.array(data['currentSmoker'])

array([0, 0, 1, ..., 1, 1, 0])

In [27]:
##Confusion matrix
res_log.pred_table()

array([[1431.00, 713.00],
       [988.00, 1106.00]])

In [33]:
tab = pd.DataFrame(res_log.pred_table())
tab.columns = ['Predicted 0', 'Predicted 1']
tab = tab.rename(index ={0: 'Actual 0',1 :'Actual 1'})
tab

          Predicted 0  Predicted 1
Actual 0       1431.0        713.0
Actual 1        988.0       1106.0

In [34]:
### Percent of accuarcy
acc = np.array(tab)
acc_train = (acc[0,0]+acc[1,1])/acc.sum()
acc_train

0.5986314299197735

##The model accuracy is not that good...it not confused in only 60% of predictions

In [43]:
res_log.predict([[70,0]])

array([0.34])

In [54]:
x= [78,45,56,34,23]
y = [0,1,0,1,0]
dic = {'Age':x,'sex':y}
dat = pd.DataFrame(dic)
dat['Prediction'] = res_log.predict(dat)
dat

   Age  sex  Prediction
0   78    0    0.321152
1   45    1    0.617980
2   56    0    0.368799
3   34    1    0.642571
4   23    0    0.445046

**The conclusion:**

> We have come to the conclusion that males have 2 times higher possibility of being a smoker than a women given same age